### ISSUE TITLE
Redmine 3.2.0: plugin causes invalid HTML on issue pages

### ISSUE THREAD

**Issue by mfb** [jrupesh/event_notifications#15]
Under Redmine 3.2.0, the plugin seems to cause invalid HTML on issue pages - `<div>` tags as child elements of a `<table>` element - and a visibly broken layout.

**Comment by jrupesh** [comment]
Hi, 
Thanks. I will update to Redmine 3.2 and keep you posted.

**Comment by jrupesh** [comment]
Issue corrected with tag v3.2.0. 
Thank You.
