### ISSUE TITLE
Problems with multilanguage use

### ISSUE THREAD

**Issue by whoevelmanns** [jrupesh/event_notifications#18]
Hi Rupesh,
I like your plugin, but we have found a problem.
If a user with english language, he couldn´t see any automatic watchers with language german and vice versa.
Also the event only published to a other with the same language.
Have you a hint for me to fix this problem?
regards

Werner

**Comment by jrupesh** [comment]
Hi,
This is really strange.
Are you using any other plugins?
Thanks.
