### ISSUE TITLE
cannot access to configuation page

### ISSUE THREAD

**Issue by actikool** [jrupesh/event_notifications#24]
Hi,
i've installed the event notification pluggin (3.0 and 3.2) in my redmine 3.2 but when i go on configuration page i've got a 404 error message
any idea?

**Comment by sbutcher** [comment]
i had the same issue. i renamed the plugin "mv event_notifications-3.0.0 event_notifications" and ran the "rake redmine:plugins:migrate RAILS_ENV=production" again and it worked.

**Comment by actikool** [comment]
Hi !!
i've tried what you explain and it works !!!
thank you very much !
