### ISSUE TITLE
Flushing internal routes?

### ISSUE THREAD

**Issue by Artusamak** [jrupesh/event_notifications#28]
Hi there, thank you for this plugin, i wished i could definitely use it!

I'm running an (almost) up to date Redmine (3.3.0.stable) for which i tried to install your plugin (i can't recal if it was the 3.2 version or a checkout from master :/) but I had an error when i was trying to access to my account to configure the notifications, so i removed the module very sad and frustrated to not be able to use it. I can't tell you the error, i don't know where Redmine logs are (i'm not in love with Ruby). :)
So i saw that you had a 3.x branch and tried to reinstall the module after checkouting the HEAD version of the branch. But... (of course, there is a but). But after restarting Redmine, when i try to access to the configuration page to enable it, i get a 404 for this path: settings/plugin/event_notifications.
So i'm wondering, is it an old path from a previous version? Why could i get this error? Is there an internal cache to flush that would be missing?

Thanks for the help, i so badly want to enjoy this module. :)
Have a nice day!

**Comment by mcdizzu** [comment]
Hi @Artusamak

I got the same error and the log said _Started GET "/settings/plugin/event_notifications" --> Missing template, responding with 404_.
Unlike almost all other plugins, which are installed under "redmine_pluginname", this plugin here has to be called only "event_notifications".
First I installed it under _redmine_event_notifications_ and that does not work. With _event_notifications_ all seems fine. Maybe that helps you.

/mcd

**Comment by Artusamak** [comment]
Yes, you're right. But now i get the same error as before when i enable the notifications and go to My account to configure them i get an internal error page.

Here is the log of the error:
`
App 27712 stderr: Started GET "/my/account" for xxxxxxxxx at 2016-11-30 22:33:30 +0100
App 27712 stderr: Processing by MyController#account as HTML
App 27712 stderr:   Current user: artusamak (id=3)
App 27712 stderr:   Rendered users/_preferences.html.erb (5.8ms)
App 27712 stderr:   Rendered plugins/event_notifications/app/views/my/_general_settings.html.erb (17.2ms)
App 27712 stderr:   Rendered plugins/event_notifications/app/views/users/_mail_notifications.html.erb (21.4ms)
App 27712 stderr:   Rendered plugins/event_notifications/app/views/my/_notification_settings.html.erb (21.7ms)
App 27712 stderr:   Rendered common/_tabs.html.erb (39.9ms)
App 27712 stderr:   Rendered plugins/event_notifications/app/views/my/account.html.erb within layouts/base (45.8ms)
App 27712 stderr: Completed 500 Internal Server Error in 97ms (ActiveRecord: 50.6ms)
App 27712 stderr:
App 27712 stderr: ActionView::Template::Error (undefined method `events' for #<Member:0x006d5c3b0082a0>):
App 27712 stderr:     20:                   else { $( \".event_#{project.id}\" ).hide();$( \".event_#{project.id} input\" ).prop( \"checked\", false );^M
App 27712 stderr:     21:                   $( \".event_#{project.id} select option\" ).prop( \"selected\", false ); }" }^M
App 27712 stderr:     22: ^M
App 27712 stderr:     23:           bool_val = @user.notified_events_projects_ids.include?(project.id)^M
App 27712 stderr:     24: ^M
App 27712 stderr:     25:           hidden_field_tag( 'user[notified_project_ids][]', "#{value}", :id => "hidden_#{project.id}" ) +^M
App 27712 stderr:     26:           content_tag('label',^M
App 27712 stderr:   plugins/event_notifications/lib/event_notification/patches/user_patch.rb:32:in `block in notified_events_projects_ids'
App 27712 stderr:   plugins/event_notifications/lib/event_notification/patches/user_patch.rb:32:in `notified_events_projects_ids'
App 27712 stderr:   plugins/event_notifications/app/views/users/_mail_notifications.html.erb:23:in `block (2 levels) in _plugins_event_notifications_app_views_users__mail_notifications_html_erb__4546850365458486591_60121454632200'
App 27712 stderr:   app/helpers/application_helper.rb:283:in `block in render_project_nested_lists'
App 27712 stderr:   app/helpers/application_helper.rb:268:in `each'
App 27712 stderr:   app/helpers/application_helper.rb:268:in `render_project_nested_lists'
App 27712 stderr:   plugins/event_notifications/app/views/users/_mail_notifications.html.erb:12:in `block in _plugins_event_notifications_app_views_users__mail_notifications_html_erb__4546850365458486591_60121454632200'
App 27712 stderr:   plugins/event_notifications/app/views/users/_mail_notifications.html.erb:11:in `_plugins_event_notifications_app_views_users__mail_notifications_html_erb__4546850365458486591_60121454632200'
App 27712 stderr:   plugins/event_notifications/app/views/my/_notification_settings.html.erb:5:in `_plugins_event_notifications_app_views_my__notification_settings_html_erb__3755366662636639546_60121454590880'
App 27712 stderr:   app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb___4393711213072313380_60121447261780'
App 27712 stderr:   app/views/common/_tabs.html.erb:16:in `each'
App 27712 stderr:   app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb___4393711213072313380_60121447261780'
App 27712 stderr:   app/helpers/application_helper.rb:325:in `render_tabs'
App 27712 stderr:   plugins/event_notifications/app/views/my/account.html.erb:24:in `block in _plugins_event_notifications_app_views_my_account_html_erb___2296902269718990984_60121446143220'
App 27712 stderr:   app/helpers/application_helper.rb:1051:in `labelled_form_for'
App 27712 stderr:   plugins/event_notifications/app/views/my/account.html.erb:14:in `_plugins_event_notifications_app_views_my_account_html_erb___2296902269718990984_60121446143220'
App 27712 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
App 27712 stderr:
`

Hopes it can help.

**Comment by jrupesh** [comment]
Hi,

Please run the migrations.

I.e

rake redmine:plugins:migrate RAILS_ENV=production

Thanks

**Comment by Artusamak** [comment]
Brilliant!
Thank you it works. <3
