### ISSUE TITLE
Issue on wiki updates

### ISSUE THREAD

**Issue by nkgokul** [jrupesh/event_notifications#34]
Whenever wikis are updated we are getting the following issue.

ArgumentError (wrong number of arguments (1 for 0)):
  plugins/a_common_libs/lib/acl/patches/models/project_patch.rb:12:in `notified_users_with_acl'
  plugins/event_notifications/lib/event_notification/patches/wiki_content_patch.rb:18:in `notified_users_with_events'
  app/models/mailer.rb:247:in `wiki_content_updated'
  app/models/mailer.rb:497:in `initialize'
  config/initializers/10-patches.rb:163:in `deliver'
  app/models/wiki_content.rb:170:in `send_notification'
  app/models/wiki_page.rb:220:in `block in save_with_content'
  app/models/wiki_page.rb:216:in `save_with_content'

**Comment by jrupesh** [comment]
Issue corrected.
Thanks.
