### ISSUE TITLE
can't enter any issue after installing the event_notification plugin

### ISSUE THREAD

**Issue by pulsarinformatique** [jrupesh/event_notifications#36]
Hi

I can't enter any issue after installing the event_notification plugin :

Here is the environment:

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  event_notifications            3.2.1
  redmine_mail_checker           1.0.0-devel
  redmine_people                 1.3.2

Here is the LOG file :

Processing by IssuesController#show as HTML
  Parameters: {"id"=>"3893"}
  Current user: cyril (id=11)
  Rendered issues/_action_menu.html.erb (9.5ms)
  Rendered plugins/event_notifications/app/views/issues/show.html.erb within layouts/base (197.3ms)
Completed 500 Internal Server Error in 601ms (ActiveRecord: 43.4ms)

ActionView::Template::Error (undefined method `render_custom_fields_rows' for #<#<Class:0x00005634de120638>:0x00005634de103970>
Did you mean?  render_custom_fields_tabs
               render_custom_field_values):
    68:     end
    69:   end
    70: end %>
    71: <%= render_custom_fields_rows(@issue) %>
    72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    73: </div>
    74:
  plugins/event_notifications/app/views/issues/show.html.erb:71:in `_plugins_event_notifications_app_views_issues_show_html_erb___4279914145695593894_47392531926640'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Did I forgot something ?

thanks

cyril

**Comment by pulsarinformatique** [comment]
I must add I didn't forgot to do :


bundle exec rake redmine:plugins:migrate NAME=event_notifications RAILS_ENV=production

reload Apache2

thanks

cyril

**Comment by pulsarinformatique** [comment]
Ok

the first error in render_half_width_custom_fields_rows was a use of render_custom_fields_rows which doesn't exist anymore in recent redmine releases

use instead  : 
render_half_width_custom_fields_rows
or
render_full_width_custom_fields_rows


but now I'm facing another bug  : 

ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    166:     <%= auto_discovery_link_tag(:atom, {:format => 'atom', :key => User.current.rss_key}, :title => "#{@issue.project} - #{@issue.tracker} ##{@issue.id}: #{@issue.subject}") %>
    167: <% end %>
    168:
    169: <%= context_menu issues_context_menu_path %>
  app/helpers/application_helper.rb:1301:in `context_menu'
  plugins/event_notifications/app/views/issues/show.html.erb:169:in `_plugins_event_notifications_app_views_issues_show_html_erb___4382723610424917084_47353327550540'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Seems the plugin is definitively too old !

Thanks 

cyril

**Comment by jrupesh** [comment]
Issue corrected in latest commit.
Thanks.
