### ISSUE TITLE
Plugin fails function properly with Redmine 3.4.4 when creating new project or clicking on settings.

### ISSUE THREAD

**Issue by victorlee816** [jrupesh/event_notifications#39]
Hi,

My environment is 
Environment:
  Redmine version                3.4.4.stable.17206
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

And my log files says:
`Started GET "/projects/new" for 10.10.50.109 at 2018-03-14 16:17:44 -0700
Processing by ProjectsController#new as HTML
  Current user: vlee (id=6)
  Rendered projects/_form.html.erb (57.2ms)
  Rendered projects/new.html.erb within layouts/base (58.0ms)
Completed 500 Internal Server Error in 78ms (ActiveRecord: 6.5ms)

ActionView::Template::Error (undefined local variable or method `format_store' for #<Project:0x007f8699e6f880>
Did you mean?  format_time):
    33: <% @project.custom_field_values.each do |value| %>
    34:   <p><%= custom_field_tag_with_label :project, value %></p>
    35: <% end %>
    36: <%= call_hook(:view_projects_form, :project => @project, :form => f) %>
    37: </div>
    38:
    39: <% if @project.new_record? && @project.safe_attribute?('enabled_module_names') %>
  plugins/event_notifications-master/lib/event_notification/patches/project_patch.rb:21:in `notify_non_member'
  lib/redmine/views/labelled_form_builder.rb:34:in `check_box'
  plugins/event_notifications-master/lib/event_notification/hooks/event_notification_hook_listener.rb:69:in `view_projects_form'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/projects/_form.html.erb:36:in `_app_views_projects__form_html_erb__2727322041610028890_70108049069000'
  app/views/projects/new.html.erb:4:in `block in _app_views_projects_new_html_erb___878032926884700745_70108049182580'
  app/helpers/application_helper.rb:1190:in `labelled_form_for'
  app/views/projects/new.html.erb:3:in `_app_views_projects_new_html_erb___878032926884700745_70108049182580'
`

I am using the latest master version of the plugin. Any suggestion as to what the issue is?

Also, the plugin's config button doesn't work either.

**Comment by jrupesh** [comment]
Hi,
Can you check the project settings with the latest commit in master branch?
Also what is the error in the Settings?
Thanks.

**Comment by victorlee816** [comment]
Sorry.  I pulled the master branch again and reinstalled the plugin.  It seems to work fine.  Thanks a lot.

**Comment by srulean** [comment]
I am seeing this same error message (undefined local variable for "format_store") when I attempt to access project settings.  However - I *just* cloned the repo, so I would assume that I have the most recent master branch content.  "git status" states I am up-to-date with master branch.

My env:

Environment:
  Redmine version                3.3.3.devel
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    development
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.11.0

**Comment by srulean** [comment]
I uninstalled it, re-cloned it, re-installed it, configured it - still same error.
